### ISSUE TITLE
[Android] Crashlytics show crash 

### ISSUE THREAD

**Issue by vishnunew** [MaikuB/flutter_local_notifications#1522]
**Describe the bug**
My app getting so many crash after updating to latest version of flutter_local_notification. Here is details.

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4495)
       at android.app.ActivityThread.access$1500(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:223)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1007)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:41)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4486)
       at android.app.ActivityThread.access$1500(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Sample code to reproduce the problem**
### Initialisation 

```dart
String? timeZoneName;
    try {
      tz.initializeTimeZones();
      timeZoneName = await SettingsPlatformChannel.getTimeZone();
      if (timeZoneName == null) {
        return;
      }
      tz.setLocalLocation(tz.getLocation(timeZoneName));
    } catch (e) {
      throw InsightException.make(e,
          additionalInformation: "Error while setLocalLocation timezone found ${timeZoneName}");
    }

var androidSettings = const AndroidInitializationSettings('ic_notification');
      var iosSettings = const IOSInitializationSettings(
        requestAlertPermission: false,
        requestBadgePermission: false,
        requestSoundPermission: false,
      );
      var initializationSettings = InitializationSettings(
        android: androidSettings,
        iOS: iosSettings,
      );
      await _plugin.initialize(
        initializationSettings,
        onSelectNotification: (payload) async {
          if (payload != null) {
            localNotificationTap.add(NotificationTapNavigationInfo(uri: payload));
          }
        },
      );
```

### Showing notification
```dart
  var androidPlatformChannelSpecifics = const AndroidNotificationDetails(_channelId, _channelName,
        channelDescription: _channelDescription,
        importance: Importance.max,
        priority: Priority.high,
        channelShowBadge: true);
    var iOSPlatformChannelSpecifics = const IOSNotificationDetails();
    var platformChannelSpecifics = NotificationDetails(
      android: androidPlatformChannelSpecifics,
      iOS: iOSPlatformChannelSpecifics,
    );
    var random = Random();

    if (pushNotification.notification != null &&
        pushNotification.notification!.title != null &&
        pushNotification.notification!.body != null) {
      if (pushNotification.notification!.title!.isEmpty || pushNotification.notification!.body!.isEmpty) {
        return;
      }
      return _plugin.show(random.nextInt(1000), pushNotification.notification!.title,
          pushNotification.notification!.body, platformChannelSpecifics,
          payload: pushNotification.data!.uri);
    } else if (pushNotification.data?.body != null &&
        pushNotification.data?.title != null &&
        pushNotification.data?.uri != null) {
      return _plugin.show(
          random.nextInt(1000), pushNotification.data!.title, pushNotification.data!.body, platformChannelSpecifics,
          payload: pushNotification.data!.uri);
    }
```

### Showing scheduled notification
``` dart
 var androidPlatformChannelSpecifics = const AndroidNotificationDetails('daily_reminder', 'Daily Reminder',
        channelDescription: 'Get reminder notification',
        importance: Importance.max,
        priority: Priority.high);
    var iOSPlatformChannelSpecifics = const IOSNotificationDetails();
    var platformChannelSpecifics = NotificationDetails(
      android: androidPlatformChannelSpecifics,
      iOS: iOSPlatformChannelSpecifics,
    );
    return await _plugin.zonedSchedule(dailyReminderNotificationId, 'Daily Reminder', content,
        scheduledTime.nextInstanceOfTimeDaily(), platformChannelSpecifics,
        payload: payload,
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
        matchDateTimeComponents: DateTimeComponents.time);
```

**Comment by MaikuB** [comment]
You will need to provide a link to a minimal app that can reproduce the issue not just code snippets. Also make sure you are on the latest build. The issue you're seeing may well be the one that was resolved in 9.3.2

**Comment by MaikuB** [comment]
Closing due to lack of response

**Comment by kartik1225** [comment]
I had the same issue,

It might be causing because you forgot to invoke `getNotificationAppLaunchDetails()` in the main file

add this in `main.dart` (also found in the [example](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/lib/main.dart#L65))
```
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

void main async () {
   ...
    await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
   ...
}

```
Edit:

Also don't forget to correctly map the icon path in android project
`app/src/main/res/mipmap/notification_icon.png`

example_screen.dart
```
Future<void> _showProgressNotification() async {
  const int maxProgress = 5;
  for (int i = 0; i <= maxProgress; i++) {
    await Future<void>.delayed(const Duration(seconds: 1), () async {
      final AndroidNotificationDetails androidPlatformChannelSpecifics =
      AndroidNotificationDetails('progress channel', 'progress channel',
          channelDescription: 'progress channel description',
          channelShowBadge: false,
          icon: '@mipmap/notification_icon',  // <-- add icon name here
          importance: Importance.max,
          priority: Priority.high,
          onlyAlertOnce: true,
          showProgress: true,
          maxProgress: maxProgress,
          progress: i);
      final NotificationDetails platformChannelSpecifics =
      NotificationDetails(android: androidPlatformChannelSpecifics);
      await flutterLocalNotificationsPlugin.show(
          0,
          'progress notification title',
          'progress notification body',
          platformChannelSpecifics,
          payload: 'item x');
    });
  }
}

// call this in widget 
_showProgressNotification();


```
