### ISSUE TITLE
Error: android.app.RemoteServiceException: Bad notification posted from package com.sergiuiacob.words: Couldn't create icon: StatusBarIcon

### ISSUE THREAD

**Issue by sergiuiacob1** [MaikuB/flutter_local_notifications#178]
Hey! I've been using this package to send daily notifications in my [app](https://play.google.com/store/apps/details?id=com.sergiuiacob.words). Some devices (Xperia X Compact, Galaxy Note 8) have been receiving this error:

```
03-02 11:00:40.209  3503  3503 E AndroidRuntime: Process: com.sergiuiacob.words, PID: 3503
03-02 11:00:40.209  3503  3503 E AndroidRuntime: android.app.RemoteServiceException: Bad notification posted from package com.sergiuiacob.words: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.sergiuiacob.words id=0x7f0a0000) visible user=0 )
03-02 11:00:40.209  3503  3503 E AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1783)
03-02 11:00:40.209  3503  3503 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:105)
03-02 11:00:40.209  3503  3503 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:251)
03-02 11:00:40.209  3503  3503 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6589)
03-02 11:00:40.209  3503  3503 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
03-02 11:00:40.209  3503  3503 E AndroidRuntime:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-02 11:00:40.209  3503  3503 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Do you have any ideas why this would happen? I created the notification icon by creating a new `Image Asset` called `icon_notification` inside Android Studio then using it like so:
```
var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        '1', 'Words', 'Receive notification with the daily words',
        icon: 'icon_notification');
```

What I've managed to find out so far is that the error occurs when the app is cleared from memory.
Using version `0.5.2`

**Comment by sergiuiacob1** [comment]
It might be important HOW I'm sending these notifications. My daily notification has today's date as its body. Therefore, I am scheduling 30 different notifications. See [here](https://github.com/MaikuB/flutter_local_notifications/issues/165) why.

```
Future<void> _scheduleNotifications(
      TimeOfDay _notificationTime, BuildContext context) async {
    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        '1', 'Words', 'Receive notification with the daily words',
        icon: 'icon_notification');
    var iOSPlatformChannelSpecifics = IOSNotificationDetails();
    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);

    List<DateTime> notificationsTime = [];
    for (int i = 0; i < 30; ++i)
      notificationsTime.add(
        DateTime(
          DateTime.now().year,
          DateTime.now().month,
          DateTime.now().day,
          _notificationTime.hour,
          _notificationTime.minute,
        ).add(Duration(days: i)),
      );

    for (int i = 0; i < 30; ++i) {
      if (DateTime.now().isAfter(notificationsTime[i])) continue;
      await flutterLocalNotificationsPlugin.schedule(
          i,
          AppLocalization.of(context).notificationTitle,
          DateFormat.yMMMMd(AppLocalization.of(context).locale.toString())
              .format(notificationsTime[i]),
          notificationsTime[i],
          platformChannelSpecifics);
    }
  }
```

**Comment by sergiuiacob1** [comment]
Is it possible that something like this happens:
1. Creating the `notificationDetails` in memory somewhere, at address `A`.
2. Scheduling first notification that uses `notificationDetails` from address `A`.
3. Clearing the app from memory. At address `A` there isn't any `notificationDetails` anymore.
4. Showing the first notification. Scheduling the second with `notificationDetails` from address `A`. But I don't have `notificationDetails` at the `A` address! Therefore it can't create the notification icon.

?

I have no idea if this makes sense or not, but I'm in the process of brain-storming 😄

**Comment by MaikuB** [comment]
Your hypothesis is something that could easily be validated and is something I've already tested whilst developing the plugin. This could be done by scheduling the notification and terminating the app before the notification is shown to see if it will show up around the time it got scheduled for.

I suspect the resource ID for your icon had changed between when the notification for scheduled (which is when the plugin tries to get it) and when the notification is about to be shown. I'm not sure how this is happening in your scenario (maybe the app got updated). Do you have steps to reproduce? I've got an idea on a solution (resolve the id for the icon just before showing the notification). Will look into creating a branch for this that you could try out when I get the chance to. If you'd be willing to assist in testing this then that would be much appreciated.

What kind of image are you using for the notification icon? I assume it's been replaced under  /resources/drawable?

**Comment by sergiuiacob1** [comment]
The source image for the icon is a 512x512 PNG file. The app was indeed updated.
Previously, there was the 1.3 version. I wasn't specifying any custom icon for the notifications. The current version is 2.0, where I created an `Image Asset` for my custom notification icon. So yeah, the app was indeed updated.

My OnePlus 3T has a thing called "Deep Clear" for when clearing the recent apps. I enabled that, I scheduled a notification and then cleared everything. The notification wasn't even shown. That's normal behaviour, however, I believe.

I'd be glad to help you out :) but I'm unsure of how to test this.

**Comment by sergiuiacob1** [comment]
Oh, something important which I forgot to mention: the crash occurs even at the first notification scheduled.

**Comment by MaikuB** [comment]
Let me get back to you. It might be possible to test without your involvement but initial thought was if you have a created a beta release for your app in the Google Play store

- you could release the current version to beta, install it and schedule notifications
- release an updated beta version of the app that will reference an updated version of this plugin
- test to see if notifications still appear

This may not be required although it would be a more realistic test. I'm going to see if resource IDs remain the same or change when a debug build is redeployed to the same device. If it changes then I could reproduce the scenario more easily

**Comment by MaikuB** [comment]
I've missed the other message when I replied but when you say the app crashes even at the first notification, does that happen even when the app is running? I've actually installed your app and tried to schedule notifications whilst it was running and that was fine. I also scheduled it and terminated the app and notifications still appeared. This was on a Pixel 2 XL

**Comment by sergiuiacob1** [comment]
Actually, I gave it some thought. That comment might not be so important as I thought. I asked somebody who had an Xperia X Compact to schedule a notification. It worked for him when the app was in foreground. But scheduling a notification and closing the app resulted in a crash for him. I don't know if the crash is from showing the first notification or from scheduling the second.

I, myself, couldn't replicate the issue with an OnePlus 3T.

**Comment by MaikuB** [comment]
Sounds like the same scenario as me I can't reproduce the issue with your app as well. I did a fresh install though

**Comment by MaikuB** [comment]
I've pushed a branch (https://github.com/MaikuB/flutter_local_notifications/tree/178). May be worth trying out in your app by referencing through git and specifying the branch as per [this link](https://www.dartlang.org/tools/pub/dependencies#git-packages). However, some of the issues you've described where closing the app causes a crash may be due to something, possibly not to do with this plugin even

**Comment by sergiuiacob1** [comment]
I need to first find somebody with either a Xperia X Compact or a Galaxy Note 8 and test this out. I could easily build an apk with the branch above.

**Comment by eggenstein** [comment]
I may have the same issue. I get reports in Google Play Store only (I cannot reproduce it on any of my devices or emulators). 
My logs don't have any details on the exception though:
> android.app.RemoteServiceException: 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1881)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6944)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

One important point is that this only happens for Android 8.0. 
And only Galaxy A5+A6 so far. My sample is rather small though.

**Comment by eggenstein** [comment]
Maybe related or maybe not. They talk about notifications, too, but also about Services.
[Solution for android.app.RemoteServiceException ?](https://www.b4x.com/android/forum/threads/solution-for-android-app-remoteserviceexception.95321/)

**Comment by eggenstein** [comment]
Maybe also related:

[Bad Notification: Couldn't expand RemoteViews for: StatusBarNotification. on Android Nougat](https://stackoverflow.com/questions/46873429/bad-notification-couldnt-expand-remoteviews-for-statusbarnotification-on-and)

[https://github.com/OneSignal/OneSignal-Android-SDK/issues/263#issuecomment-369096027](https://github.com/OneSignal/OneSignal-Android-SDK/issues/263#issuecomment-369096027)

They talk about resource IDs changing because of app upgrade and then an old alarm triggering a notification with an old resource ID. Maybe my solution for re-scheduling notifications after app upgrade could help: [Notifications lost after app update on Android?](https://github.com/MaikuB/flutter_local_notifications/issues/188)

**Comment by sergiuiacob1** [comment]
> I may have the same issue. I get reports in Google Play Store only (I cannot reproduce it on any of my devices or emulators).
> My logs don't have any details on the exception though:
> 
> > android.app.RemoteServiceException:
> > at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1881)
> > at android.os.Handler.dispatchMessage (Handler.java:105)
> > at android.os.Looper.loop (Looper.java:164)
> > at android.app.ActivityThread.main (ActivityThread.java:6944)
> > at java.lang.reflect.Method.invoke (Method.java)
> > at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
> > at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
> 
> One important point is that this only happens for Android 8.0.
> And only Galaxy A5+A6 so far. My sample is rather small though.

I also had reports for this issue on Android 7.1, so it doesn't happen only for 8.0

**Comment by MaikuB** [comment]
@eggenstein i had already made change to not save resource ids but was trying to see if i could get help from others to check if it solves the issue. I've seen mixed messages on if things scheduled through the alarm manager would be lost on an app update but that IMO is a separate issue

**Comment by MaikuB** [comment]
I've released a new version that should now store the name of the resources as opposed to the ids that i'm pretty certain is what caused. Unfortunately the fix will only retroactively apply to notifications that were scheduled that don't use the default icon specified via the `initialize`. Based on the code you've posted @sergiuiacob1, I believe this fix should work in your case since you've specified the icon per notification

**Comment by sergiuiacob1** [comment]
I'll take a look at this when I'll update the app. I'll try to do a test before and after the package update. Thank you for the notice!

**Comment by eggenstein** [comment]
I'm seeing a declining number of reports although my user base increases. Looks good.
Issue still only happening on Android 8.0 and 8.1 although majority of user base is on 9.0.

**Comment by MaikuB** [comment]
closing this as i believe the issue is fixed. unfortunately since it's not a retroactive fix it will likely require an uninstall and reinstall for users that had the app with older versions of the plugin.
